### ISSUE TITLE
FsCheck tests for Regex in Reggie.Tests crash

### ISSUE THREAD

**Issue by jack-pappas** [jack-pappas/facio#20]
In Reggie.Tests, the FsCheck-based tests for the ``Regex`` type crash. However, the FsCheck-based tests for the ``CharSet`` type do run correctly. Registration of the generators for both types are done at the same time, in the same way -- so it's unclear why the ``Regex`` tests are crashing.

The error message for all of the tests in the ``RegexRandomizedTests`` module is:
```
System.Exception : Geneflect: type not handled System.Collections.Generic.IEnumerable`1[System.Char]
   at FsCheck.ReflectArbitrary.reflectObj@102-4.Invoke(String message)
   at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
   at FsCheck.Common.memoizeWith(IDictionary`2 memo, FSharpFunc`2 f, a n)
   at FsCheck.ReflectArbitrary.reflectGen(FSharpFunc`2 getGenerator)
   at <StartupCode$Reggie-Tests>.$TestSetup.CharSet@42.Invoke(Unit unitVar) in TestSetup.fs: line 42
   at FsCheck.GenBuilder.delay@56.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@23.Invoke(Int32 n, StdGen r)
   at FsCheck.Gen.go@193[b](FSharpList`1 gs, FSharpList`1 acc, Int32 size, StdGen r0)
   at FsCheck.Gen.sequence@200.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@23.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@23.Invoke(Int32 n, StdGen r)
   at <StartupCode$FsCheck>.$Gen.Map@23.Invoke(Int32 n, StdGen r)
   at FsCheck.GenBuilder.bind@51.Invoke(Int32 n, StdGen r0)
   at FsCheck.Runner.test@102-1.GenerateNext(ref IEnumerable`1 next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.TakeWhile@1490.GenerateNext(ref IEnumerable`1 next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.Fold(FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at FsCheck.Runner.runner(Config config, a prop)
   at FsCheck.Runner.check(Config config, a p)
   at TestHelpers.assertProp(String testName, Testable property) in TestHelpers.fs: line 119
   at Tests.Reggie.RegexRandomizedTests.a language AND-ed with itself then simplified returns the original language() in Regex.fs: line 75
```

**Comment by kurtschelfthout** [comment]
Change this line: https://github.com/jack-pappas/facio/blob/master/Reggie.Tests/TestSetup.fs#L42 to

    let! chars = Arb.generate<char[]>
